# https://docs.codecov.io/docs/commit-status
coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: 0%
        base: 0%
        # advanced
        branches: []
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: []
        paths: []
