checksumBehavior: update

nodeLinker: pnp

packageExtensions:
  "@babel/plugin-syntax-import-assertions@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@sentry/nextjs@*":
    peerDependenciesMeta:
      next:
        optional: true
      react:
        optional: true
  "@walletconnect/browser-utils@*":
    dependencies:
      tslib: "*"
  "@walletconnect/client@*":
    dependencies:
      tslib: "*"
  "@walletconnect/core@*":
    dependencies:
      tslib: "*"
  "@walletconnect/iso-crypto@*":
    dependencies:
      "@walletconnect/encoding": "*"
      tslib: "*"
  "@walletconnect/socket-transport@*":
    dependencies:
      tslib: "*"
  "@walletconnect/utils@*":
    dependencies:
      tslib: "*"
  jest-config@*:
    dependencies:
      ts-node: "*"
  next-sitemap@*:
    dependencies:
      "@next/env": "*"
  react-smooth@*:
    dependencies:
      prop-types: "*"
  recharts@*:
    peerDependenciesMeta:
      prop-types:
        optional: true
  ts-node@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
  tss-react@*:
    peerDependenciesMeta:
      "@mui/material":
        optional: true
      next:
        optional: true
      react-dom:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - arm
    - arm64
    - x64
    - ia32
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.5.0.cjs
