enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  "@graphql-codegen/cli@*":
    peerDependencies:
      "@babel/core": "*"
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
  "@graphql-tools/code-file-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/git-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/github-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/graphql-tag-pluck@*":
    peerDependencies:
      "@babel/core": "*"
  graphql-config@*:
    peerDependencies:
      "@types/node": "*"
      typescript: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
