nodeLinker: pnp

packageExtensions:
  "@babel/plugin-syntax-import-assertions@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  cosmiconfig-typescript-loader@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
      ts-node:
        optional: true
      typescript:
        optional: true
  jest-config@*:
    dependencies:
      ts-node: "*"
  react-smooth@*:
    dependencies:
      prop-types: "*"
  recharts@*:
    peerDependenciesMeta:
      prop-types:
        optional: true
  ts-node@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
      "typescript":
        optional: true
  tss-react@*:
    peerDependenciesMeta:
      "@mui/material":
        optional: true
      next:
        optional: true
      react-dom:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - arm
    - arm64
    - x64
    - ia32
  libc:
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-3.3.1.cjs
