nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs

packageExtensions:
  "@graphql-codegen/cli@*":
    peerDependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
  graphql-config@*:
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
