nodeLinker: pnp

packageExtensions:
  "@graphql-codegen/cli@*":
    dependencies:
      "@types/node": ^18.11.18
      ts-node: ^10.9.1
      typescript: ^4.9.4
  "@graphql-tools/graphql-tag-pluck@*":
    dependencies:
      "@babel/core": ^7.19.6
  graphql-config@*:
    dependencies:
      "@types/node": ^18.11.18
      typescript: ^4.9.4
  jest-config@*:
    dependencies:
      ts-node: ^10.9.1
      typescript: ^4.9.4
  recharts@*:
    dependencies:
      prop-types: ^15.8.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - arm
    - arm64
    - x64
    - ia32
  libc:
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-3.3.1.cjs
