enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.2.4.cjs

packageExtensions:
  '@babel/plugin-syntax-import-assertions@*':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  cosmiconfig-typescript-loader@*:
    peerDependenciesMeta:
      '@types/node':
        optional: true
      ts-node:
        optional: true
      typescript:
        optional: true
  ts-node@*:
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true
