nmHoistingLimits: workspaces

nodeLinker: pnp

packageExtensions:
  "@babel/plugin-syntax-import-assertions@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@jest/types@*":
    dependencies:
      istanbul-lib-coverage: "*"
      istanbul-reports: "*"
      yargs: "*"
  "@types/yargs@*":
    dependencies:
      yargs-parser: "*"
  "@types/istanbul-reports@*":
    dependencies:
      istanbul-lib-report: "*"
  "@types/istanbul-lib-report@*":
    dependencies:
      istanbul-lib-coverage: "*"
  "@jest/test-result@*":
    dependencies:
      istanbul-lib-coverage: "*"
      jest-haste-map: "*"
      jest-resolve: "*"
  "@types/babel__core@*":
    dependencies:
      "@babel/generator": "*"
      "@babel/template": "*"
      "@babel/traverse": "*"
  "@types/cacheable-request@*":
    dependencies:
      keyv: "*"
      http-cache-semantics: "*"
      responselike: "*"
  "@types/color@*":
    dependencies:
      color-name: "*"
      color-convert: "*"
  "@types/color-convert@*":
    dependencies:
      color-name: "*"
  "@types/d3-interpolate@*":
    dependencies:
      d3-color: "*"
  "@types/d3-scale@*":
    dependencies:
      d3-time: "*"
  "@types/d3-shape@*":
    dependencies:
      d3-path: "*"
  "@types/jsdom@*":
    dependencies:
      tough-cookie: "*"
      jsdom: "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  "@types/react-dom@*":
    dependencies:
      react: "*"
  "@types/react-is@*":
    dependencies:
      react: "*"
  "@types/react-test-renderer@*":
    dependencies:
      react: "*"
  "@types/react-transition-group@*":
    dependencies:
      react: "*"
  "@types/react-virtualized-auto-sizer@*":
    dependencies:
      react: "*"
  "@types/react-window@*":
    dependencies:
      react: "*"
  "@types/react-window-infinite-loader@*":
    dependencies:
      react: "*"
      react-dom: "*"
      react-window: "*"
  cosmiconfig-typescript-loader@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
      ts-node:
        optional: true
      typescript:
        optional: true
  debug@*:
    dependencies:
      supports-color: "*"
  jest-config@*:
    dependencies:
      ts-node: "*"
  next@*:
    peerDependenciesMeta:
      sharp:
        optional: true
  next-translate@*:
    dependencies:
      "@types/react": "*"
      pkg-dir: "*"
  ts-jest@*:
    dependencies:
      "@jest/transform": "*"
      "@jest/types": "*"
      "@types/babel__core": "*"
  ts-node@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
  tss-react@*:
    dependencies:
      "@mui/material": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: all

pnpMode: loose

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - arm
    - arm64
    - x64
    - ia32
  libc:
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-3.3.1.cjs
