enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs

packageExtensions:
  "@graphql-codegen/cli@*":
    peerDependencies:
      "@types/node": "*"
      ts-node: "*"
      typescript: "*"
      "@babel/core": "*"
  graphql-config@*:
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  "@graphql-tools/graphql-tag-pluck@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/code-file-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/git-loader@*":
    peerDependencies:
      "@babel/core": "*"
  "@graphql-tools/github-loader@*":
    peerDependencies:
      "@babel/core": "*"
