nodeLinker: pnp

nmHoistingLimits: workspaces

packageExtensions:
  '@babel/plugin-syntax-import-assertions@*':
    peerDependenciesMeta:
      '@babel/core':
        optional: true
  cosmiconfig-typescript-loader@*:
    peerDependenciesMeta:
      '@types/node':
        optional: true
      ts-node:
        optional: true
      typescript:
        optional: true
  ts-node@*:
    peerDependenciesMeta:
      '@types/node':
        optional: true
      typescript:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpMode: loose

supportedArchitectures:
  cpu:
    - arm
    - arm64
    - ia32
    - mips
    - mipsel
    - ppc
    - ppc64
    - s390
    - s390x
    - x64

yarnPath: .yarn/releases/yarn-3.3.0.cjs
