nodeLinker: pnp

packageExtensions:
  "@babel/plugin-syntax-import-assertions@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  axios@*:
    dependencies:
      buffer: ^5.7.1
  cosmiconfig-typescript-loader@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
      ts-node:
        optional: true
      typescript:
        optional: true
  eslint@*:
    dependencies:
      locate-path: ^7.1.1
      path-exists: ^5.0.0
  debug@*:
    dependencies:
      supports-color: ^8.0.0
  next@*:
    peerDependenciesMeta:
      sharp:
        optional: true
  next-translate@*:
    dependencies:
      pkg-dir: ^4.2.0
  ts-node@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: loose

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - arm
    - arm64
    - x64
    - ia32
  libc:
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-3.3.1.cjs
