export {
  HOME,
  BLOCKS,
  BLOCK_DETAILS,
  VALIDATOR_DETAILS,
  VALIDATORS,
  TRANSACTIONS,
  TRANSACTION_DETAILS,
  PROPOSALS,
  PROPOSAL_DETAILS,
  ACCOUNT_DETAILS,
  PARAMS,
  PROFILE_DETAILS,
  ADDRESS_DETAILS,
} from 'ui/utils/go_to_page';
export const PROVIDERS = '/providers';
