# name: Docker-Production

# on:
#   push:
#     tags:
#       - assetmantle-mantle-1-v*

# jobs:
#   Build-and-Publish:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Prepare tags
#         id: prep
#         run: |
#           DOCKER_IMAGE=forbole/big-dipper-2.0-cosmos
#           VERSION=edge
#           if [[ $GITHUB_REF == refs/tags/* ]]; then
#             VERSION=${GITHUB_REF#refs/tags/}
#           fi
#           TAGS="${DOCKER_IMAGE}:${VERSION}"
#           echo ::set-output name=version::${VERSION}
#           echo ::set-output name=tags::${TAGS}
#           echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
#       - name: Prepare docker build env
#         id: dockerPrep
#         run: |
#           NEXT_PUBLIC_GRAPHQL_URL=
#           NEXT_PUBLIC_GRAPHQL_WS=
#           NEXT_PUBLIC_RPC_WEBSOCKET=
#           NEXT_PUBLIC_CHAIN_TYPE=
#           NODE_ENV="production"
#           PORT=3000
#           if [[ $GITHUB_REF == refs/tags/assetmantle-mantle-1* ]]; then
#             NEXT_PUBLIC_GRAPHQL_URL="https://gql.assetmantle.forbole.com/v1/graphql"
#             NEXT_PUBLIC_GRAPHQL_WS="wss://gql.assetmantle.forbole.com/v1/graphql"
#             NEXT_PUBLIC_RPC_WEBSOCKET="wss://rpc.assetmantle.forbole.com/websocket"
#             NEXT_PUBLIC_CHAIN_TYPE="mainnet"
#           fi
#           echo ::set-output name=NEXT_PUBLIC_GRAPHQL_URL::${NEXT_PUBLIC_GRAPHQL_URL}
#           echo ::set-output name=NEXT_PUBLIC_GRAPHQL_WS::${NEXT_PUBLIC_GRAPHQL_WS}
#           echo ::set-output name=NEXT_PUBLIC_RPC_WEBSOCKET::${NEXT_PUBLIC_RPC_WEBSOCKET}
#           echo ::set-output name=NEXT_PUBLIC_CHAIN_TYPE::${NEXT_PUBLIC_CHAIN_TYPE}
#           echo ::set-output name=NODE_ENV::${NODE_ENV}
#           echo ::set-output name=PORT::${PORT}
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ steps.prep.outputs.tags }}
#           build-args: |
#             "NEXT_PUBLIC_GRAPHQL_URL=${{ steps.dockerPrep.outputs.NEXT_PUBLIC_GRAPHQL_URL }}"
#             "NEXT_PUBLIC_GRAPHQL_WS=${{ steps.dockerPrep.outputs.NEXT_PUBLIC_GRAPHQL_WS }}"
#             "NEXT_PUBLIC_RPC_WEBSOCKET=${{ steps.dockerPrep.outputs.NEXT_PUBLIC_RPC_WEBSOCKET }}"
#             "NEXT_PUBLIC_CHAIN_TYPE=${{ steps.dockerPrep.outputs.NEXT_PUBLIC_CHAIN_TYPE }}"
#             "NODE_ENV=${{ steps.dockerPrep.outputs.NODE_ENV }}"
#             "PORT=${{ steps.dockerPrep.outputs.PORT }}"
#           labels: |
#             org.opencontainers.image.source=${{ github.event.repository.html_url }}
#             org.opencontainers.image.created=${{ steps.prep.outputs.created }}
#             org.opencontainers.image.revision=${{ github.sha }}
#       - name: Deploy to Akash 🌐
#         env:
#           ASSETMANTLE_AKASH_WEBHOOK_URL: ${{ secrets.ASSETMANTLE_AKASH_WEBHOOK_URL }}
#           AKASH_WEBHOOK_SECRET: ${{ secrets.AKASH_WEBHOOK_SECRET }}
#         run: |
#             BRANCH=${GITHUB_REF}
#             WEBHOOK_URL=''
#             if [[ $GITHUB_REF == refs/tags/assetmantle-mantle-1* ]]; then
#               echo 'Deploying to Assetmantle mantle-1'
#               WEBHOOK_URL=$ASSETMANTLE_AKASH_WEBHOOK_URL
#             fi
#               curl -i -X POST -H "Content-Type: application/json" -d '{"parameters":{"tag": "${{ steps.prep.outputs.version }}"}}' -k $WEBHOOK_URL -u "deploy:$AKASH_WEBHOOK_SECRET"

