name: Akash-Desmos
on:
  workflow_run:
    workflows: ["Docker-Production"]
    types: [completed]
    push:
      branches:
        - "!*"
      tags:
        - "desmos*"
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare tags
        id: prep
        run: |
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo ::set-output name=version::${VERSION}
      - name: Deploy to Akash 🌐
        run: |
          echo "deploying to akash!"

# jobs:
#   Desmos-Publish:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Prepare tags
#         id: prep
#         run: |
#           VERSION=edge
#           if [[ $GITHUB_REF == refs/tags/* ]]; then
#             VERSION=${GITHUB_REF#refs/tags/}
#           fi
#           echo ::set-output name=version::${VERSION}
#       - name: Deploy to Akash 🌐
#         run: |
#           echo "deploying to akash!"

        # curl -i -X POST -H "Content-Type: application/json" -d '{"parameters":{"tag": "${{ steps.prep.outputs.version }}"}}' -k ${{ secrets.WEBHOOK_URL }} -u "deploy:${{ secrets.WEBHOOK_SECRET }}"

