name: "Lint PR"
# Lint PR workflow runs linting over a single PR in order to make sure that the title respects
# the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification.
# This workflow is run every time a PR is opened, edited or updated somehow.

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint ✅
        uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}