name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
      DEBUG: pw:webserver
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      NEXT_TELEMETRY_DISABLED: 1
      ENV NODE_ENV: production
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install modules
      run: corepack enable && yarn --immutable
    - name: Install Playwright Browsers
      run: yarn dlx playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
