name: ValidateProjects
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      chain_type:
        required: true
        type: string
    outputs:
      chain_type: ${{ jobs.validate.outputs.chain_type }}
jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      chain_type: ${{ steps.vars.outputs.chain_type }}
    steps:
      - uses: actions/checkout@v3
      - name: steps.vars.outputs.projects
        id: vars
        run: |
          # assign chain_type
          node <<EOF | tee -a $GITHUB_OUTPUT
          const chainType = process.env.NEXT_PUBLIC_CHAIN_TYPE?.toLowerCase() || 'mainnet';
          const chainJson = require('./apps/' + process.env.PROJECT_NAME + '/src/chain.json');
          const { chains, ...settings } = chainJson;
          let chain = chains.find((c) => c.chainType?.toLowerCase() === chainType);
          if (!chain && chainType !== 'testnet') {
            chain = chains.find((c) => c.chainType?.toLowerCase() === 'testnet');
          }
          if (!chain) [chain] = chains;
          console.log('chain_type=' + (chain?.chainType?.toLowerCase() || 'mainnet'));
          EOF
        env:
          PROJECT_NAME: ${{ inputs.project }}
          NEXT_PUBLIC_CHAIN_TYPE: ${{ inputs.chain_type }}
